version: '3.8'

services:
  app:
    image: ${DOCKERHUB_USERNAME:-yourusername}/scrapper:latest
    platform: linux/arm64
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      AUTH_URL: ${AUTH_URL:-http://localhost:3000}
      ABC_AUCTIONS_API_URL: ${ABC_AUCTIONS_API_URL:-https://app-api.abcauctions.co.zw}
      ABC_AUCTIONS_BASE_URL: ${ABC_AUCTIONS_BASE_URL:-https://app.abcauctions.co.zw}

    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
